import { useEffect, useState } from "react";

export function useLocalState<T>(key: string, initial: T) {
  const [state, setState] = useState<T>(() => {
    if (typeof window === "undefined") return initial;
    try {
      const raw = localStorage.getItem(key);
      return raw ? (JSON.parse(raw) as T) : initial;
    } catch {
      return initial;
    }
  });
  useEffect(() => {
    try {
      localStorage.setItem(key, JSON.stringify(state));
    } catch {}
  }, [key, state]);
  return [state, setState] as const;
}

export type Product = {
  _id?: string;
  id: string;
  name: string;
  category: string; // dynamic categories managed by admin
  subcategory?: string;
  note?: string;
  huid?: string;
  purity: string; // 22K / 18K / 925
  grossWeight: number;
  netWeight: number;
  stoneWeight: number;
  makingCharge: number;
  makingChargePct?: number;
  gstPct: number;
  ratePerGram: number;
  stock: number;
  barcode: string;
  imageUrl?: string;
  imageUrls?: string[];
};

export type Customer = {
  _id?: string;
  id?: string;
  name: string;
  mobile?: string;
  phone?: string;
  address?: string;
  phone2?: string;
  gstNumber?: string;
  pan?: string;
  notes?: string;
  createdAt?: string;
};

export type MakingChargeType = "PERCENTAGE" | "PER_GRAM" | "FIXED" | "PER_PIECE" | "WASTAGE";

export type InvoiceItem = {
  productId: string;
  name: string;
  purity?: string;
  netWeight: number;
  grossWeight?: number;
  stoneWeight?: number;
  ratePerGram: number;
  makingCharge: number;
  makingChargePct?: number;
  makingChargeType?: MakingChargeType;
  makingChargeValue?: number;
  stoneCharge: number;
  gstPct: number;
  qty: number;
  huid?: string;
  hmc?: number;
};

export type InvoicePayment = {
  date: string;
  amount: number;
  mode: string;
  note?: string;
};

export type Invoice = {
  _id?: string;
  id: string;
  number: string;
  type: "GST" | "NON-GST";
  customerId?: string;
  customerName: string;
  customerMobile: string;
  customerAddress?: string;
  items: InvoiceItem[];
  discount: number;
  oldGoldAmount: number;
  paymentMode: "Cash" | "UPI" | "Card" | "EMI";
  subtotal: number;
  gstAmount: number;
  total: number;
  amountPaid?: number;
  balanceDue?: number;
  payments?: InvoicePayment[];
  customerSignature?: string;
  authorizedSignatory?: string;
  createdAt: string;
  linkedOrderId?: string;
};

export type Expense = {
  _id?: string;
  id: string;
  date: string; // ISO
  expenseType?: "Direct" | "Indirect";
  category: string; // Rent, Salary, Freight, Hallmarking...
  description: string;
  amount: number;
  paymentMode: "Cash" | "UPI" | "Card" | "Bank";
  payeeName?: string;
  voucherNo?: string;
};

export type Advance = {
  id?: string; // Make id optional as it's often generated by the backend
  date: string;
  customerId?: string;
  customerName: string;
  customerMobile: string;
  metal: "Gold" | "Silver";
  purity: string;
  ratePerGram: number; // locked at advance day
  amount: number; // advance amount paid
  weightLocked: number; // amount/rate
  note?: string;
  status: "Active" | "Redeemed" | "Cancelled";
};

export type GirviItem = {
  id?: string;
  itemType: "Gold" | "Silver" | "Mixed";
  itemCategory?: string;
  itemDescription: string;
  grossWeight: number;
  netWeight: number;
  purity: string;
  marketValue?: number;
};

export type Girvi = {
  id: string;
  date: string;
  loanNo: string;
  customerName: string;
  customerMobile: string;
  customerMobile2?: string;
  customerAddress?: string;
  items?: GirviItem[];
  itemType?: "Gold" | "Silver" | "Mixed";
  itemCategory?: string;
  itemDescription?: string;
  grossWeight?: number;
  netWeight?: number;
  purity?: string;
  marketValue?: number;
  loanAmount: number;
  interestPct: number; // monthly %
  interestPeriod?: "Yearly" | "Monthly" | "Daily";
  documentType?: "Invoice" | "Bill" | "Receipt";
  documentNumber?: string;
  imageUrl?: string;
  dueDate?: string;
  status: "Active" | "Closed" | "Auctioned";
  note?: string;
  forwardedTo?: string;
  forwardedShopName?: string;
  forwardedShopGstNo?: string;
  forwardedShopAddress?: string;
  forwardedDate?: string;
  forwardedAmount?: number;
  forwardedInterestPct?: number;
  forwardedInterestPeriod?: "Yearly" | "Monthly" | "Daily";
  isForwardedSettled?: boolean;
  forwardedSettledDate?: string;
  forwardedSettledInterest?: number;
  forwardedImageUrl?: string;
  customerSignature?: string;
  authorizedSignatory?: string;
};

export type SupplierTransaction = {
  id?: string;
  _id?: string;
  date: string;
  type: "Credit" | "Debit";
  kind?: "Weight" | "Payment";
  metal?: "Gold" | "Silver";
  purity?: string;
  weight?: number;
  amount?: number;
  paymentMode?: string;
  note?: string;
};

export type Supplier = {
  _id?: string;
  id: string;
  name: string;
  company?: string;
  mobile: string;
  email?: string;
  category?: string;
  gstNumber?: string;
  address?: string;
  companyNo?: string;
  note?: string;
  outstanding: number;
  balanceGold?: number;
  balanceSilver?: number;
  transactions?: SupplierTransaction[];
  createdAt: string;
};

export type Karigar = {
  _id?: string;
  id: string;
  name: string;
  mobile: string;
  specialty: string; // Goldsmith, Polisher, Stone Setter...
  category?: string;
  address?: string;
  companyName?: string;
  email?: string;
  gstNumber?: string;
  note?: string;
  username?: string;
  password?: string;
  pendingWeight: number; // grams issued not returned
  createdAt: string;
};

export type Repair = {
  _id?: string;
  id?: string;
  ticketNo: string;
  date: string;
  customerName: string;
  customerMobile: string;
  customerAddress?: string;
  metal?: "Gold" | "Silver" | "Diamond" | "Platinum" | "Other";
  purity?: string;
  itemDescription: string;
  itemWeight: number;
  receivedWeight?: number;
  deliveredWeight?: number;
  goldAddedWeight?: number;
  problem: string;
  estimate?: number;
  estimatedCost?: number;
  actualCost?: number;
  karigarLabourCharge?: number;
  advance: number;
  deliveryDate?: string;
  karigarId?: string;
  status: "Received" | "In Progress" | "Ready" | "Delivered";
  beforePhotoUrl?: string;
  afterPhotoUrl?: string;
  note?: string;
  createdAt?: string;
  customerSignature?: string;
  authorizedSignatory?: string;
};

export type Order = {
  _id?: string;
  id: string;
  orderNo: string;
  date: string;
  customerName: string;
  customerMobile: string;
  customerAddress?: string;
  itemDescription: string;
  metal: "Gold" | "Silver" | "Diamond" | "Platinum" | "Other";
  purity: string;
  expectedGrossWeight?: number;
  expectedNetWeight?: number;
  sizeLength?: string;
  hallmarkRequired?: boolean;
  rateLockStatus?: "Locked" | "Open";
  lockedGoldRate?: number;
  oldGoldWeight?: number;
  oldGoldPurity?: string;
  oldGoldValuation?: number;
  makingCharge?: number;
  wastagePct?: number;
  estimatedTotalAmount?: number;
  estimatedWeight?: number;
  estimatedPrice?: number;
  fixedPrice?: number;
  advancePaid: number;
  karigarId?: string;
  dueDate?: string;
  status: "Pending" | "In Progress" | "Ready" | "Delivered" | "Cancelled";
  note?: string;
  sampleImageUrl?: string;
  customerSignature?: string;
  authorizedSignatory?: string;
};


export type Purchase = {
  _id?: string;
  id: string;
  billNo: string;
  date: string;
  supplierId?: string;
  supplierName?: string;
  supplierGstin?: string;
  metal: "Gold" | "Silver" | "Diamond" | "Stone" | "Other";
  purity?: string;
  hsnCode?: string;
  weight: number;
  ratePerGram: number;
  makingCharge: number;
  taxableValue: number;
  gstPct: number;
  cgst: number;
  sgst: number;
  igst: number;
  total: number;
  paymentMode: "Cash" | "UPI" | "Card" | "Bank" | "Credit";
  note?: string;
  docType?: "Entry" | "Order" | "Return" | "OldGold";
  category?: "Metal" | "Diamond" | "Stone";
  status?: "Draft" | "Pending Approval" | "Approved" | "Rejected" | "Ordered" | "Received" | "Cancelled" | "Completed";
  needsApproval?: boolean;
  approvedBy?: string;
  approvedAt?: string;
  rejectionReason?: string;
  linkedDocId?: string;
  customerId?: string;
  customerName?: string;
  deductionPct?: number;
};

export type MetalRates = {
  updatedAt: string;
  gold24: number;
  gold22: number;
  gold20: number;
  gold18: number;
  silver: number;
};

export const uid = () =>
  Math.random().toString(36).slice(2, 8) + Date.now().toString(36).slice(-4);

// Returns the making charge on a PER-UNIT basis (i.e. before multiplying by qty),
// since calcItem multiplies the whole base (metal + making + stone + hmc) by qty.
// FIXED is divided by qty here so that, after that multiplication, it nets out to
// exactly `value` regardless of how many pieces are on the line.
export function computeMakingCharge(params: {
  type?: MakingChargeType;
  value: number;
  netWeight: number;
  ratePerGram: number;
  qty: number;
}) {
  const { type = "PERCENTAGE", value, netWeight, ratePerGram, qty } = params;
  switch (type) {
    case "PER_GRAM":
      return netWeight * value;
    case "PER_PIECE":
      return value;
    case "FIXED":
      return value / (qty || 1);
    case "WASTAGE":
      return (netWeight * (value / 100)) * ratePerGram;
    case "PERCENTAGE":
    default:
      return (netWeight * ratePerGram * value) / 100;
  }
}

export function calcItem(it: InvoiceItem, isGst: boolean) {
  const base = it.netWeight * it.ratePerGram + it.makingCharge + it.stoneCharge + (it.hmc || 0);
  const line = base * it.qty;
  const gst = isGst ? (line * it.gstPct) / 100 : 0;
  return { line, gst, total: line + gst };
}

export function inr(n: number) {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 2,
  }).format(n || 0);
}

export interface InvoiceSettings {
  headerStyle: "classic" | "centered" | "modern";
  themeColor: "gold" | "slate" | "purple" | "emerald" | "blue";
  showLogo: boolean;
  logoSize: "sm" | "md" | "lg";
  invoiceTitle: string;
  tagline: string;
  
  // Table Columns Toggle
  showHuid: boolean;
  showPurity: boolean;
  showGrossWeight: boolean;
  showWastage: boolean;
  showNetWeight: boolean;
  showRatePerGram: boolean;
  showMakingCharges: boolean;
  showGstBreakdown: boolean;
  showOldGoldSection: boolean;
  showPaymentQr: boolean;

  // Custom Labels
  huidHeaderLabel: string;
  makingChargeHeaderLabel: string;
  
  // Footer & Terms
  termsAndConditions: string;
  customFooterNote: string;
  signature1Label: string;
  signature2Label: string;
  bankAccountDetails: string;

  // Payment QR & UPI Settings
  upiId?: string;
  qrCodeUrl?: string;
}

export const defaultInvoiceSettings: InvoiceSettings = {
  headerStyle: "classic",
  themeColor: "gold",
  showLogo: true,
  logoSize: "md",
  invoiceTitle: "INVOICE",
  tagline: "Govt. Approved BIS Hallmarked Jewellery Showroom",
  showHuid: true,
  showPurity: true,
  showGrossWeight: true,
  showWastage: true,
  showNetWeight: true,
  showRatePerGram: true,
  showMakingCharges: true,
  showGstBreakdown: true,
  showOldGoldSection: true,
  showPaymentQr: true,
  huidHeaderLabel: "HUID / Purity",
  makingChargeHeaderLabel: "Making Charges",
  termsAndConditions: "1. Goods once sold will not be taken back without original invoice.\n2. 100% BIS 916 Hallmarked Jewellery Guarantee.\n3. Making charges non-refundable on returns.\n4. Subject to local jurisdiction only.",
  customFooterNote: "Thank you for shopping with us! Visit again for authentic jewellery.",
  signature1Label: "Customer Signature",
  signature2Label: "For Authorized Signatory",
  bankAccountDetails: "Bank: HDFC Bank | A/C: 50200012345678 | IFSC: HDFC0001234",
  upiId: "",
  qrCodeUrl: "",
};

export function getCleanInvoiceTitle(title?: string): string {
  if (!title || title.trim().toUpperCase() === "TAX INVOICE") {
    return "INVOICE";
  }
  return title;
}

export function getUpiQrCodeUrl(params: {
  upiId?: string;
  shopName?: string;
  phone?: string;
  qrCodeUrl?: string;
  amount?: number;
}): string {
  if (params.qrCodeUrl && params.qrCodeUrl.trim()) {
    return params.qrCodeUrl.trim();
  }
  const pa = params.upiId && params.upiId.trim() ? params.upiId.trim() : params.phone && params.phone.trim() ? `${params.phone.trim()}@ybl` : "";
  if (!pa) return "";
  const pn = encodeURIComponent(params.shopName || "Jewellery Shop");
  const am = params.amount && params.amount > 0 ? `&am=${params.amount}` : "";
  const upiUri = `upi://pay?pa=${pa}&pn=${pn}${am}&cu=INR`;
  return `https://api.qrserver.com/v1/create-qr-code/?size=250x250&margin=2&data=${encodeURIComponent(upiUri)}`;
}
